<a href="https://colab.research.google.com/github/IgorGorskov/vvedenie_v_python/blob/main/DZ_44.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import pandas as pd
import random
lst = ['robot'] * 10
print(lst)
lst += ['human'] * 10
print(lst)
random.shuffle(lst)
data = pd.DataFrame({'whoAmI':lst})
data

['robot', 'robot', 'robot', 'robot', 'robot', 'robot', 'robot', 'robot', 'robot', 'robot']
['robot', 'robot', 'robot', 'robot', 'robot', 'robot', 'robot', 'robot', 'robot', 'robot', 'human', 'human', 'human', 'human', 'human', 'human', 'human', 'human', 'human', 'human']

   whoAmI
0   human
1   human
2   human
3   human
4   robot
5   human
6   robot
7   robot
8   human
9   robot
10  robot
11  robot
12  robot
13  robot
14  robot
15  human
16  human
17  human
18  human
19  robot

In [25]:
# как я понял по условию,
# программа работает только для датафрейма в один столбец
# который создается в выше

my_lst = list()
lst_1 = list() #подсчет людей
lst_2 = list() #подсчет роботов
for i in range(data.shape[0]): #кол-во строк 
  for j in range(data.shape[1]): #кол-во столбцов
    if data.iloc[i][j] == 'human':
      lst_1.append('1')
      lst_2.append('0')
    elif data.iloc[i][j] == 'robot':
      lst_1.append('0')
      lst_2.append('1')
one_hot_data = pd.DataFrame({'IamHuman':lst_1,'IamRobot':lst_2})
data_combined = pd.concat([data, one_hot_data], axis=1)
data_combined

   whoAmI IamHuman IamRobot
0   human        1        0
1   human        1        0
2   human        1        0
3   human        1        0
4   robot        0        1
5   human        1        0
6   robot        0        1
7   robot        0        1
8   human        1        0
9   robot        0        1
10  robot        0        1
11  robot        0        1
12  robot        0        1
13  robot        0        1
14  robot        0        1
15  human        1        0
16  human        1        0
17  human        1        0
18  human        1        0
19  robot        0        1